Refactor and modernize Travis-CI
- Remove 'sudo', it has no effect anymore
- Define 'os' to be explicit (which is 'linux' as default anyway)
- Use 'bionic' (otherwise 'dist' defaults to 'xenial' which is very old)
- Clean away unnecessary notification settings
- Bump PHP versions to cover the latest stable ones
- Rename 'matrix' as 'jobs' which is the modern Travis-CI lingo
- Remove Ruby virtual machine installation step, not needed anymore

Validated with https://config.travis-ci.com/explore

PHP 8 and nightly are still ignored, as they fail on:

  Exception: Predis library not found
  wp-content/object-cache.php(185)

This error already existed before this commit, so this ignoring
it does not make the codebase any worse off.